# Generated by Django 5.2.7 on 2025-10-04 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="USSDSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "current_state",
                    models.CharField(
                        choices=[
                            ("main_menu", "Main Menu"),
                            ("weather_info", "Weather Information"),
                            ("drought_alerts", "Drought Alerts"),
                            ("crop_advice", "Crop Advice"),
                            ("registration", "User Registration"),
                            ("profile_update", "Profile Update"),
                            ("help", "Help"),
                            ("ended", "Session Ended"),
                        ],
                        default="main_menu",
                        max_length=20,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=5)),
                ("context_data", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("total_requests", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="USSDUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("preferred_language", models.CharField(default="en", max_length=5)),
                ("full_name", models.CharField(blank=True, max_length=100)),
                ("farm_size_acres", models.FloatField(blank=True, null=True)),
                ("primary_crops", models.CharField(blank=True, max_length=200)),
                ("receive_alerts", models.BooleanField(default=True)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.region",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
