# Generated by Django 5.2.7 on 2025-10-04 10:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "region_type",
                    models.CharField(
                        choices=[
                            ("country", "Country"),
                            ("county", "County"),
                            ("ward", "Ward"),
                            ("village", "Village"),
                        ],
                        max_length=20,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "area_sq_km",
                    models.FloatField(
                        blank=True, help_text="Area in square kilometers", null=True
                    ),
                ),
                ("population", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.region",
                    ),
                ),
            ],
            options={
                "ordering": ["region_type", "name"],
                "unique_together": {("name", "region_type", "parent_region")},
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("farmer", "Farmer"),
                            ("admin", "Administrator"),
                            ("extension_officer", "Extension Officer"),
                        ],
                        default="farmer",
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sw", "Swahili"),
                            ("ki", "Kikuyu"),
                            ("lu", "Luhya"),
                            ("luo", "Luo"),
                            ("ka", "Kamba"),
                            ("me", "Meru"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("receive_whatsapp_alerts", models.BooleanField(default=True)),
                ("receive_sms_alerts", models.BooleanField(default=True)),
                ("receive_email_alerts", models.BooleanField(default=False)),
                (
                    "farm_size_acres",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                    ),
                ),
                (
                    "primary_crops",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list of crops",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.region",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__first_name", "user__last_name"],
            },
        ),
    ]
