# Generated by Django 5.2.7 on 2025-10-04 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farm_name", models.CharField(blank=True, max_length=100)),
                (
                    "farming_type",
                    models.CharField(
                        choices=[
                            ("crop", "Crop Farming"),
                            ("livestock", "Livestock"),
                            ("mixed", "Mixed Farming"),
                            ("horticulture", "Horticulture"),
                            ("dairy", "Dairy Farming"),
                        ],
                        default="crop",
                        max_length=20,
                    ),
                ),
                (
                    "irrigation_type",
                    models.CharField(
                        choices=[
                            ("rain_fed", "Rain-fed"),
                            ("drip", "Drip Irrigation"),
                            ("sprinkler", "Sprinkler"),
                            ("furrow", "Furrow Irrigation"),
                            ("mixed", "Mixed Systems"),
                        ],
                        default="rain_fed",
                        max_length=20,
                    ),
                ),
                (
                    "main_crops",
                    models.TextField(
                        blank=True,
                        help_text="List main crops grown, separated by commas",
                    ),
                ),
                (
                    "livestock_count",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of livestock (cattle, goats, sheep, etc.)",
                    ),
                ),
                (
                    "farm_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "farm_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "annual_income_bracket",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("below_50k", "Below 50,000 KSH"),
                            ("50k_100k", "50,000 - 100,000 KSH"),
                            ("100k_200k", "100,000 - 200,000 KSH"),
                            ("200k_500k", "200,000 - 500,000 KSH"),
                            ("above_500k", "Above 500,000 KSH"),
                        ],
                        max_length=20,
                    ),
                ),
                ("years_farming", models.IntegerField(blank=True, null=True)),
                ("has_smartphone", models.BooleanField(default=False)),
                ("uses_weather_apps", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["user_profile__user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="FarmerGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("registration_number", models.CharField(blank=True, max_length=50)),
                ("formation_date", models.DateField(blank=True, null=True)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.region"
                    ),
                ),
                (
                    "chairman",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chaired_groups",
                        to="farmers.farmerprofile",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="farmer_groups", to="farmers.farmerprofile"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CropCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_name", models.CharField(max_length=50)),
                ("optimal_planting_start", models.DateField()),
                ("optimal_planting_end", models.DateField()),
                (
                    "growing_days_min",
                    models.IntegerField(help_text="Minimum days to maturity"),
                ),
                (
                    "growing_days_max",
                    models.IntegerField(help_text="Maximum days to maturity"),
                ),
                (
                    "water_requirement_mm",
                    models.FloatField(
                        help_text="Total water requirement in mm for full season"
                    ),
                ),
                (
                    "critical_stages",
                    models.TextField(
                        blank=True,
                        help_text="JSON or comma-separated critical growth stages",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.region"
                    ),
                ),
            ],
            options={
                "ordering": ["crop_name", "region"],
                "unique_together": {("crop_name", "region")},
            },
        ),
        migrations.CreateModel(
            name="FarmField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("area_acres", models.FloatField(help_text="Field area in acres")),
                (
                    "soil_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("clay", "Clay"),
                            ("sandy", "Sandy"),
                            ("loam", "Loam"),
                            ("clay_loam", "Clay Loam"),
                            ("sandy_loam", "Sandy Loam"),
                            ("rocky", "Rocky"),
                        ],
                        max_length=30,
                    ),
                ),
                ("current_crop", models.CharField(blank=True, max_length=50)),
                ("planting_date", models.DateField(blank=True, null=True)),
                ("expected_harvest_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="farmers.farmerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["farmer", "field_name"],
                "unique_together": {("farmer", "field_name")},
            },
        ),
    ]
