# Generated by Django 5.2.7 on 2025-10-04 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("drought_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("drought_warning", "Drought Warning"),
                            ("water_stress", "Water Stress Alert"),
                            ("planting_advisory", "Planting Advisory"),
                            ("harvest_advisory", "Harvest Advisory"),
                            ("irrigation_reminder", "Irrigation Reminder"),
                            ("weather_warning", "Weather Warning"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity_level",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("critical", "Critical"),
                            ("emergency", "Emergency"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title_template", models.CharField(max_length=200)),
                (
                    "message_template",
                    models.TextField(
                        help_text="Use {variable_name} for dynamic content"
                    ),
                ),
                (
                    "sms_template",
                    models.CharField(
                        help_text="SMS version (max 160 characters)", max_length=160
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sw", "Swahili"),
                            ("ki", "Kikuyu"),
                            ("lu", "Luhya"),
                            ("luo", "Luo"),
                            ("ka", "Kamba"),
                            ("me", "Meru"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "auto_send",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically send when conditions are met",
                    ),
                ),
                (
                    "trigger_risk_threshold",
                    models.FloatField(
                        blank=True,
                        help_text="Risk score threshold to trigger this alert",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["alert_type", "severity_level", "language"],
                "unique_together": {("name", "language")},
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_id", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("sms_message", models.CharField(blank=True, max_length=160)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_send_time", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("total_recipients", models.IntegerField(default=0)),
                ("successfully_sent", models.IntegerField(default=0)),
                ("failed_sends", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drought_assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="drought_data.droughtriskassessment",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.region"
                    ),
                ),
                (
                    "target_users",
                    models.ManyToManyField(blank=True, to="core.userprofile"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="alerts.alerttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("ussd", "USSD"),
                            ("push", "Push Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("email_address", models.EmailField(blank=True, max_length=254)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("external_message_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="alerts.alert",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("alert", "recipient", "delivery_method")},
            },
        ),
        migrations.CreateModel(
            name="AlertFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("helpful", "Helpful"),
                            ("not_helpful", "Not Helpful"),
                            ("too_frequent", "Too Frequent"),
                            ("too_late", "Too Late"),
                            ("incorrect", "Incorrect Information"),
                            ("suggestion", "Suggestion"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="Rating 1-5 stars",
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "action_taken",
                    models.BooleanField(
                        default=False,
                        help_text="Did the user take action based on this alert?",
                    ),
                ),
                ("action_description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="alerts.alert",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("alert", "user_profile")},
            },
        ),
        migrations.CreateModel(
            name="AlertSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("drought_warning", "Drought Warning"),
                            ("water_stress", "Water Stress Alert"),
                            ("planting_advisory", "Planting Advisory"),
                            ("harvest_advisory", "Harvest Advisory"),
                            ("irrigation_reminder", "Irrigation Reminder"),
                            ("weather_warning", "Weather Warning"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_subscribed", models.BooleanField(default=True)),
                (
                    "min_severity_level",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("critical", "Critical"),
                            ("emergency", "Emergency"),
                        ],
                        default="moderate",
                        help_text="Minimum severity level to receive alerts",
                        max_length=20,
                    ),
                ),
                ("prefer_whatsapp", models.BooleanField(default=True)),
                ("prefer_sms", models.BooleanField(default=True)),
                ("prefer_email", models.BooleanField(default=False)),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True,
                        help_text="Start of quiet hours (no alerts)",
                        null=True,
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True, help_text="End of quiet hours", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_profile", "alert_type")},
            },
        ),
    ]
